Cypress.Commands.add('individualForm', () => { 
    cy.get('#name').type(Cypress.env('validName'))
    cy.get('#data').type(Cypress.env('validDate'))
    cy.get('.formulario__email > input').type(Cypress.env('validEmail'))
    cy.get('#cpf').type(Cypress.env('validCpf'))
    cy.get('#telefone').type(Cypress.env('validPhoneNumber'))
    cy.get('#cep').type(Cypress.env('validCep'))
    cy.get('.formulario__endereco_cidade').type(Cypress.env('validCity'))
    cy.get('.formulario__endereco_logradouro').type(Cypress.env('validStreet'))
    cy.get('.formulario__endereco_bairro').type(Cypress.env('validNeighborhood'))
    cy.get('.formulario__endereco_estado').type(Cypress.env('validState'))
    cy.get('.formulario__endereco_numero').type(Cypress.env('validAddressNumber'))
    cy.get('.botao-formulario').click()
})
