name: Cypress Tests

on:
  push:
    branches: main

jobs:
  cypress-run-1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Write the cypress.env.json file 
        run: |
          echo '${{ secrets.CYPRESS_ENV_FILE }}' > cypress.env.json

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          run: npm run test:form-1

  cypress-run-2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Write the cypress.env.json file 
        run: |
          echo '${{ secrets.CYPRESS_ENV_FILE }}' > cypress.env.json

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          run: npm run test:form-2