name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
          
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          validName: ${{ secrets.validName }}
          validDate": ${{ secrets.validDate }}
          validEmail": ${{ secrets.validEmail }}
          validCpf": ${{ secrets.validCpf }}
          validPhoneNumber": ${{ secrets.validPhoneNumber }}
          validCep": ${{ secrets.validCep }}
          validCity": ${{ secrets.validCity }}
          validStreet": ${{ secrets.validStreet }}
          validNeighborhood": ${{ secrets.validNeighborhood }}
          validState": ${{ secrets.validState }}
          validAddressNumber": ${{ secrets.validAddressNumber }}
        with:
          start: npm start
          run: npm run cy:run
